version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chat_db
    ports:
      - "3306:3306"
    networks:
      - chat-network

  web:
    build: .
    container_name: chat-server
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
