version: '3.8' #Carmel & Max

services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: chat_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat-network

  web:
    build: .
    container_name: chat-server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
      - MYSQL_DB=chat_db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

